"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var str = 'Hello World!';
var num1 = 234;
var num2 = 234.567;
var val = true;
console.log(str);
console.log(num1);
console.log(num2);
console.log(num2);
console.log(num1.toPrecision());
